export type NiceTagOptions = {
  name: string;       // Form relevant name of the inner checkbox input.
  label: string;      // Human-readable label displayed on the tag and announced by screen readers.
  value: string;      // String value associated with the tag (used for filtering logic).
  selected?: boolean; // Initial selected state. Defaults to false.
  required?: boolean; // Initial required state. Defaults to false.
  disabled?: boolean; // Initial disabled state. Defaults to false.
  readonly?: boolean; // Initial readonly state. Defaults to false.
  form?: string;      // The ID of the owner form (needed if the tag is not inside its DOM)
  id?: string;        // Optional stable ID to associate the label with the input. If omitted, one is autogenerated.
  className?: string; // Optional classes for the root element
};
